apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-node-app
  template:
    metadata:
      labels:
        app: ecommerce-node-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: ecommerce-node-app
        image: $IMAGE_NAME:$IMAGE_TAG
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-node-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: ecommerce-node-app
