apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-node-app-chart.fullname" . }}
  labels:
    {{- include "ecommerce-node-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "ecommerce-node-app-chart.name" . }}
